name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Configure system
      run: sudo apt install -y build-essential make cmake git libgmp-dev libmpfr-dev libboost-dev libcgal-qt5-dev
      
    - name: Download and unzip CGAL 5.2.1
      run: cd ~ && wget https://github.com/CGAL/cgal/releases/download/v5.2.1/CGAL-5.2.1.zip && unzip CGAL-5.2.1.zip
    - name: Build CGAL 5.2.1
      run: cd ~/CGAL-5.2.1 && cmake -B build -DCGAL_HEADER_ONLY=OFF -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} && cmake --build build --config ${{env.BUILD_TYPE}}
    - name: Install CGAL 5.2.1
      run: cd ~/CGAL-5.2.1/build && sudo make install

    - name: Build Project
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} && cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Run Project
      run: cd ${{github.workspace}}/build && ./Proyecto1 ../puntos.txt
